### ISSUE TITLE
项目报错。没有AppDelegate+JPush.h和.m文件

### ISSUE THREAD

**Issue by yoga0806** [anyRTC/anyRTC-P2P-iOS#2]
项目报错。没有AppDelegate+JPush.h和.m文件

**Comment by BoYuanZjq** [comment]
hi,
文件已经上传，你可以下载再试试，有什么不明白的，直接邮件回复，或者QQ:984630262
谢谢


张坚强
铂渊信息技术（上海）有限公司
地址：杨浦区殷行路1286号嘉誉国际2号楼901室
电话：13641647500
网站：https://www.anyrtc.io
邮编：200438


原始邮件
发件人:hyjnotifications@github.com
收件人:anyRTC/anyRTC-P2P-iOSanyRTC-P2P-iOS@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2019年1月8日(周二) 17:52
主题:[anyRTC/anyRTC-P2P-iOS] 项目报错。没有AppDelegate+JPush.h和.m文件 (#2)


项目报错。没有AppDelegate+JPush.h和.m文件
